#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))
new_lst= arr[::-1]
for i in range(n):
    print(new_lst[i],end=' ')
